import test from 'node:test';import assert from 'node:assert/strict';
import {blankCyber,normalizeCyber,assessCyber,CYBER_CONTROLS,CYBER_FILE} from '../public/cyber.mjs';
import {applyCyberGate} from '../worker/lifecycle-store.mjs';
import {reconcileMatrixFindings} from '../worker/matrix-findings.mjs';
const proof={id:'p',mission_id:'m',original_name:'source.json',sha256:'a'.repeat(64)};
function complete(){const d=blankCyber('m');for(const t of d.tests)Object.assign(t,{applicability:'YES',applicability_reason:'Dans le périmètre',source:'Référence vérifiée §1',scope:'Périmètre test',procedure:'Test positif et négatif',observed:'Résultat test uniquement',reviewer:'Testeur',reviewed_at:'2026-10-03T12:00:00Z',result:'COMPLIANT',evidence_ids:['p']});return d;}
test('17 exact Cyber domains start unevaluated with no manufactured evidence',()=>{const d=blankCyber('m');assert.equal(d.tests.length,17);assert.ok(d.tests.every(t=>t.result==='NOT_STARTED'&&!t.observed&&!t.evidence_ids.length));assert.equal(assessCyber(d).passed,0);assert.equal(CYBER_CONTROLS[12].title,'PRA / PCA / gestion de crise');});
test('complete Cyber fixture requires sources, review, observed tests and proof',()=>{assert.equal(assessCyber(normalizeCyber(complete(),'m',[proof]),[proof]).status,'COMPLIANT');for(const k of ['source','scope','procedure','observed','reviewer','reviewed_at','applicability_reason']){const d=complete();d.tests[0][k]='';assert.equal(assessCyber(d,[proof]).status,'NOT_STARTED',k);}});
test('Cyber rejects missing domains, foreign missions and self evidence',()=>{const d=complete();assert.throws(()=>normalizeCyber(d,'other',[proof]));assert.throws(()=>normalizeCyber(d,'m',[{...proof,mission_id:'other'}]));assert.throws(()=>normalizeCyber(d,'m',[{...proof,original_name:CYBER_FILE}]));d.tests.pop();assert.throws(()=>normalizeCyber(d,'m',[proof]));});
test('Cyber exclusions need scope justification and reviewed source',()=>{const d=complete();Object.assign(d.tests[0],{applicability:'NO',result:'NOT_APPLICABLE',observed:'',evidence_ids:[]});assert.equal(assessCyber(d,[proof]).status,'COMPLIANT');d.tests[0].source='';assert.equal(assessCyber(d,[proof]).status,'NOT_STARTED');});
test('Cyber synthetic evidence cannot conclude real compliance and a failure remains visible',()=>{const d=complete();d.mode='DEMO';assert.equal(assessCyber(d,[proof]).status,'NOT_STARTED');d.tests[0].result='NON_COMPLIANT';assert.equal(assessCyber(d,[proof]).status,'NON_COMPLIANT');});
test('Cyber gates preserve saved answers and proven nonconformity',()=>{const chain=[{reference:'DGFiP-7.3',reponse_statut:'COMPLIANT'},{reference:'DGFiP-A7',reponse_statut:'NON_COMPLIANT'}];const out=applyCyberGate(chain,{assessment:assessCyber(null)});assert.equal(out[0].reponse_statut,'NOT_STARTED');assert.equal(chain[0].reponse_statut,'COMPLIANT');assert.equal(out[1].reponse_statut,'NON_COMPLIANT');});
test('reconciliation preserves finding identity, prior closure and is idempotent',async()=>{let record={id:'f',number:'CST-HISTORIQUE',status:'CLOSED',summary:'Constat historique',closure_comment:'Contre-test historique'},events=[];const db={select:async()=>[record],patch:async(_,q,v)=>(record={...record,...v}),insert:async(_,v)=>{events.push(v);return {id:'event'};}};const args={tenantId:'t',missionId:'m',actor:'a',chain:[{reference:'DGFiP-3.9',question_id:'q'}],lifecycle:{assessment:{status:'NOT_STARTED',issues:['Messages manquants'],tests:[]}},cyber:{assessment:{tests:[]}},revision:'rev'};assert.equal((await reconcileMatrixFindings(db,args)).changed,1);assert.equal(record.number,'CST-HISTORIQUE');assert.equal(record.closure_comment,'Contre-test historique');assert.equal(record.status,'OPEN');assert.match(record.summary,/Constat historique/);assert.equal(events[0].details.previous.status,'CLOSED');assert.equal((await reconcileMatrixFindings(db,args)).unchanged,1);assert.equal(events.length,2);});
