# Questionnaire de référence DIAM.
#
# Autorité normative : Guide pratique de l'audit de conformité DGFiP v1.3.
# Approfondissement technique : PDP Integrity v3.2 PA Label.

diam_questionnaire_template <- function() {
  data.frame(
    reference = c(
      "DGFiP-RAPPORT", "DGFiP-1.1", "DGFiP-1.2", "DGFiP-1.3",
      "DGFiP-2.1", "DGFiP-2.2",
      "DGFiP-3.1", "DGFiP-3.2", "DGFiP-3.3", "DGFiP-3.4",
      "DGFiP-3.5", "DGFiP-3.6", "DGFiP-3.7", "DGFiP-3.8", "DGFiP-3.9",
      "DGFiP-4.1", "DGFiP-4.2", "DGFiP-4.3",
      "DGFiP-5.1", "DGFiP-5.2", "DGFiP-5.3", "DGFiP-5.4",
      "DGFiP-6", "DGFiP-7.1", "DGFiP-7.2", "DGFiP-7.3",
      "DGFiP-A4.1", "DGFiP-A4.2", "DGFiP-A5", "DGFiP-A6",
      "DGFiP-A7", "DGFiP-A8", "DGFiP-A9"
    ),
    chapter = c(
      "Rapport d'audit",
      rep("1. Interopérabilité des échanges", 3),
      rep("2. Authentification", 2),
      rep("3. Émission et transmission des factures", 9),
      rep("4. Données de transaction et de paiement", 3),
      rep("5. Transmission au PPF", 4),
      "6. Conservation et stockage",
      rep("7. Traçabilité et contrôle", 3),
      rep("Article 4. Accord formel et portabilité", 2),
      "Article 5. SecNumCloud",
      "Article 6. ISO/IEC 27001",
      "Article 7. Localisation des données",
      "Article 8. Conservation des preuves",
      "Article 9. Marque blanche"
    ),
    title = c(
      "Le rapport d'audit est-il prévu avec une signature électronique avancée ?",
      "La plateforme maîtrise-t-elle les formats CII, UBL et Factur-X sans perte d'intégrité ?",
      "Les raccordements à l'administration et à Chorus Pro sont-ils effectifs ?",
      "L'interopérabilité avec les autres PA et, le cas échéant, Peppol est-elle démontrée ?",
      "Le KYB/KYC vérifie-t-il l'identité et le pouvoir d'engagement du client ?",
      "Tout accès humain est-il protégé par une authentification à deux facteurs dont un dynamique ?",
      "L'authenticité, l'intégrité et la lisibilité des factures sont-elles garanties ?",
      "La contribution de la PA à la piste d'audit fiable est-elle documentée et actualisée ?",
      "Les factures signées et les certificats associés sont-ils vérifiés et conservés ?",
      "Une liste séquentielle, exhaustive et inaltérable des messages et anomalies est-elle tenue ?",
      "Les contrôles réglementaires des données de facturation sont-ils exhaustifs et documentés ?",
      "Les transformations vers les formats du socle préservent-elles toutes les données et le lisible ?",
      "Les échanges utilisent-ils uniquement des protocoles de communication sécurisés autorisés ?",
      "L'adressage s'appuie-t-il correctement sur l'annuaire central et la validité du SIREN ?",
      "Les statuts obligatoires du cycle de vie sont-ils gérés, transmis et tracés ?",
      "Les données de transaction et de paiement sont-elles identifiées et séparées ?",
      "Les données de transaction et de paiement font-elles l'objet des contrôles réglementaires ?",
      "L'agrégation par SIREN préserve-t-elle exactitude, exhaustivité et intégrité dans le temps ?",
      "Les extractions et conversions vers le PPF sont-elles fiables, traçables et intègres ?",
      "Les contrôles sur les données transmises au PPF sont-ils documentés et testés régulièrement ?",
      "Les données sont-elles transmises au PPF dans les formats autorisés ?",
      "Les délais réglementaires de transmission des flux et de l'e-reporting sont-ils respectés ?",
      "Les traitements de données personnelles respectent-ils l'article 32 et les principes du RGPD ?",
      "Les accès portail, API et EDI sont-ils contrôlés, journalisés et régulièrement testés ?",
      "L'annuaire est-il utilisé uniquement pour l'adressage, avec diffusion et conservation limitées ?",
      "Les traitements sont-ils contrôlés et leurs preuves rapidement mobilisables en cas de litige ?",
      "Chaque inscription d'adressage repose-t-elle sur un accord formel et des justificatifs KYB/KYC ?",
      "La portabilité gratuite pendant douze mois et la documentation de mobilité sont-elles assurées ?",
      "Tout hébergement cloud externalisé pertinent est-il qualifié SecNumCloud ?",
      "La certification ISO/IEC 27001 est-elle valide et couvre-t-elle le périmètre PA et ses tiers ?",
      "Les données et accès d'exploitation restent-ils dans l'Union européenne ?",
      "Les moyens de preuve sont-ils conservés six ans, intègres et rapidement restituables ?",
      "Le dispositif marque blanche respecte-t-il les obligations propres de la PA et la séparation avec la PA support ?"
    ),
    description = c(
      "DGFiP v1.3 p.5. PDP Integrity : EX-23.2, EX-19.6 et EX-19.7.",
      "DGFiP v1.3 §1.1. PDP Integrity : EX-6.x, EX-11.3 à EX-11.5, EX-B.x.",
      "DGFiP v1.3 §1.2. PDP Integrity : EX-7.x, EX-11.9, EX-18.1 à EX-18.4.",
      "DGFiP v1.3 §1.3. PDP Integrity : EX-7.x et EX-20.1 à EX-20.9.",
      "DGFiP v1.3 §2.1. PDP Integrity : EX-9.x IAM et EX-21.3.",
      "DGFiP v1.3 §2.1-2.2. PDP Integrity : EX-9.x et EX-18.9.",
      "DGFiP v1.3 §3.1. PDP Integrity : EX-11.1 à EX-11.14 et EX-19.x.",
      "DGFiP v1.3 §3.2. PDP Integrity : EX-8.x et EX-19.7.",
      "DGFiP v1.3 §3.3. PDP Integrity : EX-9.x, EX-19.6 et EX-23.x.",
      "DGFiP v1.3 §3.4. PDP Integrity : EX-8.x, EX-19.1 à EX-19.10.",
      "DGFiP v1.3 §3.5. PDP Integrity : EX-6.x, EX-11.5 à EX-11.14.",
      "DGFiP v1.3 §3.6. PDP Integrity : EX-6.x, EX-11.3, EX-11.4 et EX-B.x.",
      "DGFiP v1.3 §3.7. PDP Integrity : EX-7.x, EX-18.3 et EX-20.x.",
      "DGFiP v1.3 §3.8. PDP Integrity : EX-4.6, EX-8.14 et EX-10.x.",
      "DGFiP v1.3 §3.9. PDP Integrity : EX-11.16-17, EX-12.x et EX-20.8.",
      "DGFiP v1.3 §4.1. PDP Integrity : EX-13.x et schémas F8/F9/F10.",
      "DGFiP v1.3 §4.2. PDP Integrity : EX-13.5, EX-13.8 et EX-B.x.",
      "DGFiP v1.3 §4.3. PDP Integrity : EX-13.4-5 et EX-19.x.",
      "DGFiP v1.3 §5.1. PDP Integrity : EX-11.x, EX-13.x et EX-19.x.",
      "DGFiP v1.3 §5.2. PDP Integrity : EX-11.5-14 et EX-13.5-8.",
      "DGFiP v1.3 §5.3. PDP Integrity : EX-6.x, EX-13.x et EX-B.x.",
      "DGFiP v1.3 §5.4. PDP Integrity : EX-11.16bis-17 et EX-13.6.",
      "DGFiP v1.3 §6. PDP Integrity : EX-16.1 à EX-16.12.",
      "DGFiP v1.3 §7.1. PDP Integrity : EX-8.x, EX-9.12-13 et EX-18.7-9.",
      "DGFiP v1.3 §7.2. PDP Integrity : EX-8.14-15 et EX-10.x.",
      "DGFiP v1.3 §7.3. PDP Integrity : EX-8.x, EX-19.7 et EX-23.x.",
      "DGFiP v1.3 art.4. PDP Integrity : EX-10.x et EX-21.8.",
      "DGFiP v1.3 art.4. PDP Integrity : EX-4.11, EX-8.16 et EX-22.x.",
      "DGFiP v1.3 art.5. PDP Integrity : EX-21.6 et EX-9.20.",
      "DGFiP v1.3 art.6. PDP Integrity : EX-9.x et EX-21.5.",
      "DGFiP v1.3 art.7. PDP Integrity : EX-16.10 et EX-21.6-7.",
      "DGFiP v1.3 art.8. PDP Integrity : EX-8.15-16, EX-23.x et EX-C.x.",
      "DGFiP v1.3 art.9. PDP Integrity : EX-10.17 à EX-10.24."
    ),
    requirement = c(
      "Signature électronique avancée garantissant authenticité et intégrité.",
      "Transformation sans perte ; conformité EN 16931, CII, UBL, Factur-X et AFNOR XP Z12-012.",
      "Raccordements QUAL/PROD, Chorus Pro B2G/G2B, profils et fonctions opérationnels.",
      "Connexion PA-à-PA et compatibilité Peppol lorsque l'autre PA utilise ce réseau.",
      "KYB/KYC fiable, conservation des justificatifs et vérification du pouvoir du signataire.",
      "2FA dynamique jusqu'en 2030 puis niveau de garantie substantiel ; analyse de risque documentée.",
      "Authenticité de l'émetteur, intégrité du contenu et lisibilité jusqu'au terme de conservation.",
      "Documentation complète des contrôles, risques, systèmes, traitements et responsabilités.",
      "Validation du certificat et de la signature ; preuve de validité au moment du contrôle.",
      "Journal séquentiel alimenté au fil de l'eau, exhaustif, non modifiable et ventilé par client.",
      "Contrôles de cohérence, TVA, montants, doublons et données obligatoires.",
      "Transformation sans déperdition ; conservation du lisible original en cas de perte d'information.",
      "EDI AS2/AS4/SFTP, portail fortement authentifié ou API REST/SOAP sécurisée.",
      "Contrôle du destinataire, consultation/mise à jour de l'annuaire et justification des lignes.",
      "Gestion de Déposée, Refusée, Rejetée et Encaissée ; maîtrise des statuts facultatifs.",
      "Séparation logique et fonctionnelle des données de transaction et de paiement.",
      "Contrôles conformes aux articles 242 nonies N/P et processus entièrement décrits.",
      "Agrégation exacte, complète, durable et fondée sur un SIREN valide.",
      "Intégrité systématique, gestion des incidents et chaîne de contrôle des événements.",
      "Contrôles attendus documentés, versionnés et testés périodiquement.",
      "Respect des schémas et formats autorisés par les spécifications externes.",
      "Respect des échéances selon régime TVA, flux 1 et e-reporting.",
      "Licéité, finalité, minimisation, sécurité, chiffrement/anonymisation et effacement maîtrisés.",
      "Traçabilité complète, horodatage synchronisé et accès rapide aux journaux.",
      "Aucun usage commercial de l'annuaire et aucune mise à disposition intégrale aux clients.",
      "Preuve opposable de chaque traitement et contrôle interne sur tous les échanges.",
      "Accord formel valide, choix éclairé et justificatifs présentables à l'auditeur.",
      "Services de portabilité gratuits douze mois et documentation de mobilité sans condition.",
      "Qualification SecNumCloud pour les services cloud externalisés participant à l'activité PA.",
      "Certificat valide, organisme accrédité, périmètre PA et déclaration d'applicabilité disponibles.",
      "Absence de transfert et d'accès hors UE ; équipes d'exploitation et maintenance situées dans l'UE.",
      "Conservation pendant six ans, intégrité, indexation et restitution rapide des preuves.",
      "Accords/KYB propres, ISO 27001, RGPD, localisation UE, raccordement sécurisé et audit après la PA support."
    ),
    criticality = c(
      "HIGH", "CRITICAL", "CRITICAL", "CRITICAL", "CRITICAL", "CRITICAL",
      rep("CRITICAL", 9), rep("HIGH", 3), rep("CRITICAL", 4),
      "HIGH", "CRITICAL", "HIGH", "CRITICAL",
      "CRITICAL", "HIGH", "CRITICAL", "CRITICAL", "CRITICAL", "HIGH", "HIGH"
    ),
    verification_method = c(
      "Revue du processus de signature et test de validation du rapport.",
      "Revue de conception et tests de conversion sur échantillons représentatifs.",
      "Captures des raccordements et analyse ciblée des journaux de connexion.",
      "Tests d'interopérabilité, certificats et journaux de bout en bout.",
      "Walkthrough d'onboarding et échantillonnage de dossiers KYB/KYC.",
      "Test de connexion, revue IAM/MFA et analyse des journaux d'accès.",
      "Revue des contrôles et rejeu de factures de bout en bout.",
      "Revue documentaire, entretiens et rapprochement avec les traitements réels.",
      "Test de signature valide, expirée et révoquée ; contrôle de la preuve d'horodatage.",
      "Extraction d'un mois de journaux et rapprochement avec les flux sources.",
      "Jeux de tests positifs/négatifs et revue de la matrice de contrôles.",
      "Tests comparatifs avant/après et validation du lisible.",
      "Revue de configuration et tests API/EDI sécurisés.",
      "Tests d'adressage, de SIREN invalide et de mise à jour de l'annuaire.",
      "Rejeu des transitions et rapprochement F1/F6/CDAR.",
      "Inspection du modèle de données et tests de séparation.",
      "Jeux d'erreurs et rapprochement des résultats attendus.",
      "Recalcul indépendant d'agrégats et contrôle de complétude.",
      "Rejeu de flux et reconstruction de la chaîne d'événements.",
      "Inspection de la matrice de contrôles et des résultats de campagne.",
      "Validation XSD/JSON/Schematron sur échantillons.",
      "Analyse des horodatages sur une période et tests de rattrapage.",
      "Revue RGPD, registre, DPIA, mesures techniques et échantillon d'effacements.",
      "Extraction de journaux portail/API/EDI et tests IAM.",
      "Revue des appels annuaire, habilitations et durées de conservation.",
      "Reconstitution d'un dossier de preuve à partir d'un échantillon de flux.",
      "Échantillonnage des accords et rapprochement avec l'annuaire.",
      "Test d'export, documentation et clauses contractuelles.",
      "Revue d'architecture et des attestations des hébergeurs.",
      "Contrôle du certificat, périmètre, SoA et certifications des tiers.",
      "Revue contractuelle/architecture, géolocalisation IP et journaux d'administration.",
      "Test d'export d'un dossier ancien et vérification des empreintes/manifests.",
      "Revue contractuelle, technique et probatoire spécifique marque blanche."
    ),
    expected_evidence = c(
      "Politique de signature ; certificat ; rapport signé ; résultat de validation.",
      "Matrice des formats ; schémas ; rapports de validation ; couples source/cible ; lisibles.",
      "Profils AIFE ; configurations QUAL/PROD et Chorus Pro ; captures ; logs ; tests.",
      "Contrats et configurations PA/Peppol ; certificat AP ; résultats de tests ; logs corrélés.",
      "Procédure KYB/KYC ; dossiers échantillonnés ; pouvoirs ; accord formel ; registre de conservation.",
      "Analyse de risques ; politique IAM ; configuration MFA ; comptes ; journaux ; tests périodiques.",
      "Matrice des contrôles ; architecture ; échantillons ; traces ; empreintes ; rapports de tests.",
      "PAF ; cartographie ; matrice des risques ; procédures ; RACI ; preuves de mise à jour.",
      "Politique PKI ; chaînes de certificats ; OCSP/CRL ; horodatages ; journaux de validation.",
      "Journaux séquentiels ; fichier partenaires ; contrôles d'inaltérabilité ; exports.",
      "Catalogue des contrôles ; règles TVA ; cas de tests ; anomalies et corrections.",
      "Spécifications de mapping ; tests de non-régression ; rapports de comparaison ; lisibles.",
      "Configurations AS2/AS4/SFTP/API ; certificats ; scans TLS ; journaux ; tests.",
      "Appels annuaire ; lignes d'adressage ; validations SIREN ; logs de mise à jour.",
      "Matrice des statuts ; règles de transition ; messages CDAR/F6 ; journaux ; tests.",
      "Modèle de données ; schémas F8/F9/F10 ; exemples ; règles de séparation.",
      "Matrice des contrôles ; jeux de tests ; rapports d'erreur ; procédures.",
      "Algorithmes d'agrégation ; rapprochements ; contrôles SIREN ; empreintes ; tests.",
      "Chaîne de traitement ; corrélation ; incidents ; rejeux ; empreintes ; rapports.",
      "Documentation versionnée ; campagnes de tests ; anomalies ; validations.",
      "Schémas autorisés ; validateurs ; payloads ; rapports XSD/Schematron.",
      "Calendrier réglementaire ; ordonnanceur ; tableaux de bord SLA ; alertes ; preuves de dépôt.",
      "Registre ; DPIA ; politiques ; chiffrement ; tests d'effacement ; incidents.",
      "Politique IAM ; configurations ; journaux UTC ; SIEM ; rapports de revue d'accès.",
      "Procédure annuaire ; habilitations ; extractions ; logs ; preuves de purge.",
      "Journaux corrélés ; manifests ; payloads ; empreintes ; procédure de restitution.",
      "Accords formels ; KYB/KYC ; pouvoirs ; traces d'inscription et de retrait annuaire.",
      "Clauses de portabilité ; documentation ; export complet ; preuve de maintien douze mois.",
      "Attestation SecNumCloud ; périmètre ; architecture d'hébergement ; contrats.",
      "Certificat ISO 27001 ; rapport ; SoA ; périmètre ; accréditation ; certificats tiers.",
      "Cartographie des flux et accès ; contrats ; localisation ; logs IP ; jeux de test anonymisés.",
      "Politique de conservation ; SAE/WORM ; manifests ; empreintes ; exports ; tests de restauration.",
      "Contrat PA support ; architecture M2M ; séparation ; accords/KYB ; ISO ; logs ; audit support."
    ),
    stringsAsFactors = FALSE
  )
}
